const mongoose = require('mongoose');

// Commission — per-order commission tracking ("Order Commissions" page).
const commissionSchema = new mongoose.Schema({
  outletId: { type: mongoose.Schema.Types.ObjectId, ref: 'Outlet', required: true, index: true },
  orderId: { type: mongoose.Schema.Types.ObjectId, ref: 'Order', required: true },
  orderAmount: { type: Number, required: true },
  commissionPercent: { type: Number, required: true, default: 0 },
  commissionAmount: { type: Number, required: true, default: 0 },
  payableToOutlet: { type: Number, default: 0 },
  status: { type: String, enum: ['Pending', 'Paid', 'Cancelled'], default: 'Pending' },
  recordedOn: { type: Date, default: Date.now },

  // === SQL parity fields (mirrors MySQL table `orders`) ===
  sqlId: { type: Number, index: true, sparse: true },
  unique_id: { type: String, default: '' },
  device_id: { type: String, default: '' },
  name: { type: String, default: '' },
  email: { type: String, default: '' },
  mobile: { type: String, default: '' },
  someone_else_name: { type: String, default: '' },
  user_id: { type: Number, default: 0 },
  shop_id: { type: Number, default: 0 },
  amount: { type: Number, default: 0 },
  tax_amount: { type: Number, default: 0 },
  deduct_amount: { type: Number, default: 0 },
  total_amount: { type: Number, default: 0 },
  wallet_amount: { type: Number, default: 0 },
  online_amount: { type: Number, default: 0 },
  outlet_commission_rate: { type: Number, default: 0 },
  outlet_commission_amount: { type: Number, default: 0 },
  transaction_id: { type: String, default: '' },
  payment_type: { type: Number, default: 0 },
  tips: { type: Number, default: 0 },
  order_date: { type: String, default: '' },
  order_time: { type: String, default: '' },
  created_at: { type: Date, default: null },
  accept_time: { type: String, default: '' },
  ready_time: { type: String, default: '' },
  complete_time: { type: String, default: '' },
  abandone_time: { type: String, default: '' },
  is_abandone_count_start: { type: Number, default: 0 },
  is_order_abandoned: { type: Number, default: 0 },
  scanned_by: { type: Number, default: 0 },
  order_type: { type: Number, default: 0 },
  table_no: { type: String, default: '' },
  floor: { type: String, default: '' },
  served_by: { type: Number, default: 0 },
  is_ready: { type: Number, default: 0 },
  sqaure_order_id: { type: String, default: '' },
  cancellation_reason: { type: String, default: '' },
  deleted_by_user: { type: Number, default: 0 },
  is_active: { type: Number, default: 0 },
  is_deleted: { type: Number, default: 0 },

}, { timestamps: true });

module.exports = mongoose.model('Commission', commissionSchema);
