const mongoose = require('mongoose');

const tipSchema = new mongoose.Schema({
  outletId: { type: mongoose.Schema.Types.ObjectId, ref: 'Outlet', required: true, index: true },
  orderId: { type: mongoose.Schema.Types.ObjectId, ref: 'Order', default: null },
  userId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
  customerName: { type: String, default: null },
  employeeId: { type: mongoose.Schema.Types.ObjectId, ref: 'Employee', default: null },
  amount: { type: Number, required: true, min: 0 },
  paymentMode: { type: String, enum: ['Cash', 'Card', 'UPI', 'Wallet', 'Other'], default: 'Cash' },
  notes: { type: String, default: null },
  tipDate: { type: Date, default: Date.now, index: true },
  status: { type: String, enum: ['Recorded', 'Paid', 'Cancelled'], default: 'Recorded' },

  // === SQL parity fields (mirrors MySQL table `orders`) ===
  sqlId: { type: Number, index: true, sparse: true },
  unique_id: { type: String, default: '' },
  device_id: { type: String, default: '' },
  name: { type: String, default: '' },
  email: { type: String, default: '' },
  mobile: { type: String, default: '' },
  someone_else_name: { type: String, default: '' },
  user_id: { type: Number, default: 0 },
  shop_id: { type: Number, default: 0 },
  tax_amount: { type: Number, default: 0 },
  deduct_amount: { type: Number, default: 0 },
  total_amount: { type: Number, default: 0 },
  wallet_amount: { type: Number, default: 0 },
  online_amount: { type: Number, default: 0 },
  outlet_commission_rate: { type: Number, default: 0 },
  outlet_commission_amount: { type: Number, default: 0 },
  transaction_id: { type: String, default: '' },
  payment_type: { type: Number, default: 0 },
  tips: { type: Number, default: 0 },
  order_date: { type: String, default: '' },
  order_time: { type: String, default: '' },
  created_at: { type: Date, default: null },
  accept_time: { type: String, default: '' },
  ready_time: { type: String, default: '' },
  complete_time: { type: String, default: '' },
  abandone_time: { type: String, default: '' },
  is_abandone_count_start: { type: Number, default: 0 },
  is_order_abandoned: { type: Number, default: 0 },
  scanned_by: { type: Number, default: 0 },
  order_type: { type: Number, default: 0 },
  table_no: { type: String, default: '' },
  floor: { type: String, default: '' },
  served_by: { type: Number, default: 0 },
  is_ready: { type: Number, default: 0 },
  sqaure_order_id: { type: String, default: '' },
  cancellation_reason: { type: String, default: '' },
  deleted_by_user: { type: Number, default: 0 },
  is_active: { type: Number, default: 0 },
  is_deleted: { type: Number, default: 0 },

}, { timestamps: true });

module.exports = mongoose.model('Tip', tipSchema);
